name: CI - HTML Validation

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install HTML validator
        run: npm install -g html-validate

      - name: Validate HTML
        run: html-validate index.html